### ISSUE TITLE
.NET Framework LZ4组件无法加载。

### ISSUE THREAD

**Issue by Ivony** [aliyun/aliyun-log-csharp-sdk#6]
System.IO.FileLoadException: 未能加载文件或程序集“LZ4, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null”或它的某 一个依赖项。找到的程序集清单定义与程序集引用不匹配。 (异常来自 HRESULT:0x80131040)

**Comment by Ivony** [comment]
确认问题，NuGet上的客户端不是官方的。问题已关闭。

**Comment by dupeng0811** [comment]
不是官方的，那么怎么解决的呢。。。
